### ISSUE TITLE
pollDao.closePoll() никогда не вернёт True

### ISSUE THREAD

**Issue by morrah** [lexek/chat#57]
https://github.com/lexek/chat/blob/f2188ef2587536556ca6525024f6bf7c92c66555/src/main/java/lexek/wschat/db/dao/PollDao.java#L88
Происходит апдейт одной записи (праймари кей гарантирует, что pollId уникален) и .execute() должен вернуть либо 0, либо 1, но никогда не >1.
Но сейчас это ни на что не влияет, т.к. в сервисе, откуда происходит вызов метода, не проверяется возвращаемое значение.

**Comment by lexek** [comment]
Будет исправлено в рамках #57
